import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

prisma.$executeRaw`INSERT INTO "TestEmbedding" (text, embedding) VALUES ('test', ARRAY[1, 2, 3, 4]::extensions.vector)`
  .then((num) => console.log({ num }))
  .then(() =>
    prisma.testUser.createManyAndReturn({
      data: [
        {
          email: "jennaortega@gmail.com",
          phoneNumber: "+14349843857",
          passwordHash: "w3dnesd4y!$",
          firstName: "Jenna",
          lastName: "Ortega",
          gender: "FEMALE",
          genderIdentity: "CISGENDER",
          dateOfBirth: new Date(2002, 8, 27),
          location: "+34.0549-118.2426/",
          ethnicity: "HISPANIC",
          politcalBelief: "LIBERAL",
          religion: "DONT_WANT_TO_ANSWER",
          drinker: true,
          drinkerDealbreaker: false,
          smoker: false,
          smokerDealbreaker: false,
          weed: true,
          weedDealbreaker: false,
        },
        {
          email: "shaunashipman91@yahoo.com",
          phoneNumber: "+14724829372",
          passwordHash: "y3ll0wj4cket",
          firstName: "Shauna",
          lastName: "Shipman",
          gender: "FEMALE",
          genderIdentity: "CISGENDER",
          dateOfBirth: new Date(2004, 6, 15),
          location: "+40.5169-74.4063/",
          ethnicity: "WHITE_CAUCASIAN",
          politcalBelief: "MODERATE",
          religion: "DONT_WANT_TO_ANSWER",
          drinker: true,
          drinkerDealbreaker: false,
          smoker: true,
          smokerDealbreaker: false,
          weed: false,
          weedDealbreaker: false,
        },
        {
          email: "billie392@gmail.com",
          phoneNumber: "+12858378912",
          passwordHash: "kjs93ks941",
          firstName: "Billie",
          lastName: "Eilish",
          gender: "FEMALE",
          genderIdentity: "CISGENDER",
          dateOfBirth: new Date(1999, 11, 18),
          location: "+34.0549-118.2426/",
          ethnicity: "WHITE_CAUCASIAN",
          politcalBelief: "LIBERAL",
          religion: "ATHEIST",
          drinker: true,
          drinkerDealbreaker: false,
          smoker: false,
          smokerDealbreaker: false,
          weed: true,
          weedDealbreaker: false,
        },
        {
          email: "jennytalia464@gmail.com",
          phoneNumber: "+13897325297",
          passwordHash: "ujnk3892ka93",
          firstName: "Jenny",
          lastName: "Talia",
          gender: "NONBINARY",
          genderIdentity: "GENDER_FLUID",
          dateOfBirth: new Date(2001, 2, 12),
          location: "+40.7128-74.0060/",
          ethnicity: "MIDDLE_EASTERN",
          politcalBelief: "OTHER",
          religion: "BUDDHIST",
          drinker: false,
          drinkerDealbreaker: true,
          smoker: true,
          smokerDealbreaker: false,
          weed: true,
          weedDealbreaker: false,
        },
        {
          email: "chickenjockey2@gmail.com",
          phoneNumber: "+14982971794",
          passwordHash: "fejsn8943$jk",
          firstName: "Jaden",
          lastName: "Harrison",
          gender: "FEMALE",
          genderIdentity: "MASC",
          dateOfBirth: new Date(2000, 3, 15),
          location: "+40.7128-74.0060/",
          ethnicity: "BLACK_AFRICAN_AMERICAN_CARIBBEAN_AMERICAN",
          politcalBelief: "OTHER",
          religion: "DONT_WANT_TO_ANSWER",
          drinker: true,
          drinkerDealbreaker: false,
          smoker: false,
          smokerDealbreaker: true,
          weed: true,
          weedDealbreaker: false,
        },
      ],
    })
  )
  .then((users) => console.log({ users }))
  .catch((err) => console.error(err));
